on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
        gemfile:
          - "Gemfile.jwt.2.4"
          - "Gemfile.jwt.2.5"
          - "Gemfile.jwt.2.6"
          - "Gemfile.jwt.2.7"
          - "Gemfile.jwt.2.8"
          - "Gemfile.jwt.2.9"
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RUBY_VERSION: $${ matrix.ruby }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rspec
